version: '3.8'
services:
  redbot:
    build:
      args:
      - VERSION=${REDBASE_VERSION}
      context: ./manifest/images/redbase/
    command: main
    image: docker.io/ccarney16/redbase:${REDBASE_VERSION:-latest}
    restart: always
    volumes:
    - ./conf.d/redbot:/config:z
    - ./data/redbot:/data:z
  lavalink:
    build:
      args:
      - VERSION=${LAVALINK_VERSION}
      context: ./manifest/images/lavalink
    image: docker.io/ccarney16/lavalink:${LAVALINK_VERSION:-latest}
    volumes:
    - ./conf.d/lavalink:/config:z
    - ./data/lavalink:/data:z
